services:
  - type: web
    name: my-ai-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production 